#!/usr/bin/env bash
# Atomic commit script for par-code v0.2.1 implementation.
#
# Usage:  bash scripts/commit-v0.2.1.sh
# Review: git log --oneline origin/main..HEAD
# Undo:   git reset --soft origin/main  (keeps all changes staged)
#
# This script creates 6 atomic commits mapping to file boundaries.
# The disclosure-rule sweep is bundled into commits 5 and 6 (with notes
# in their messages) to avoid fragile `git add -p` interactive staging.
# Per global rules, a truly standalone sweep commit is preferable; this
# is a pragmatic compromise for a single-file description-line change.
#
# IMPORTANT: This script does NOT push. After review, run `git push` manually.

set -euo pipefail

cd "$(dirname "$0")/.."

if [ -z "$(git status --porcelain)" ]; then
  echo "Working tree clean — nothing to commit."
  exit 0
fi

echo "=== Staging commit 1/6: install.sh ==="
git add scripts/install.sh
git commit -m \
"feat(install): POSIX sh one-line installer for Linux + macOS

7 functions: detect_platform, resolve_prefix, fetch_latest_tag,
download_asset, verify_sha256, install_binary, maybe_update_path.
Idempotent rc-file updates with markers. Supports --prefix, --version
flags + PAR_PREFIX, PAR_MIRROR, PAR_DISABLE_UPDATE_CHECK env vars.
HTTPS + SHA256 = transport-corruption detection (not adversarial)."

echo "=== Staging commit 2/6: upgrade module + version generation + CLI ==="
git add -A lib/par_code_upgrade.ml lib/par_code_upgrade.mli \
          lib/par_code.ml lib/dune \
          test/test_par_code.ml \
          bin/cli_args.ml bin/main.ml \
          .gitignore
git commit -m \
"feat(upgrade): par_code_upgrade module + generated version + CLI subcommand

- lib/par_code_upgrade.{ml,mli}: eio-based self-update via
  Cohttp_eio.Client.call (Par.Http_client.do_request is POST-only).
  TLS reuses Par.Http_client.tls_config. Atomic replace via rename(2)
  over running binary + post-swap smoke test (3s timeout) + rollback.
  Cache at ~/.par/.latest-cache.json with 24h TTL + ETag conditional GET.
  SHA256 verification via Digestif.
- lib/par_code_version.ml: generated at build time by dune rule from
  dune-project's (version ...) field via %{version:par_code}. Replaces
  hand-written version constants in lib/par_code.ml (deleted).
- lib/dune: adds par_code_upgrade module + cohttp-eio, tls-eio, digestif
  to libraries (all transitively available via par SDK).
- bin/cli_args.ml + bin/main.ml: adds 'par upgrade' subcommand with
  --check, --to <ver>, --uninstall, --purge flags. Purely-additive
  startup version-check notice (single stderr line, gated by
  PAR_NO_UPDATE_CHECK=1, only fires in chat mode).
- test/test_par_code.ml: version assertions updated to reference
  Par_code_version.* (was Par_code.*).
- .gitignore: adds lib/par_code_version.ml (generated, never committed)."

echo "=== Staging commit 3/6: macOS + Linux build scripts ==="
git add scripts/build-macos.sh scripts/docker/linux-bundle.Dockerfile \
        scripts/checksums.sh
git commit -m \
"feat(bundle): macOS arm64 + CentOS 7 Linux build scripts

- scripts/build-macos.sh: builds par-code on macos-15 runner, bundles
  libsqlite3.0.dylib + libgmp.10.dylib via install_name_tool with
  @loader_path RPATH + @rpath install names. Produces
  par-v<ver>-darwin-arm64.zip + .sha256.
- scripts/docker/linux-bundle.Dockerfile: CentOS 7 + devtoolset-11
  build (CentOS 7's gcc 4.8.5 hard-fails OCaml 5.x configure; SCL
  provides gcc 11 while keeping glibc 2.17 baseline). Bundles
  libsqlite3.so.0 + libgmp.so.10 with \$ORIGIN RPATH via patchelf.
  Produces par-v<ver>-linux-x64.tar.gz + .sha256.
- scripts/checksums.sh: CI helper to concatenate per-target checksum
  files into single checksums.txt."

echo "=== Staging commit 4/6: release.yml ==="
git add .github/workflows/release.yml
git commit -m \
"ci(release): tag-triggered multi-platform release workflow

3 jobs: build-linux (CentOS 7 Docker build), build-macos (macos-15
runner), coordinate (concatenate checksums, upload install.sh, create
GitHub Release via softprops/action-gh-release). Triggers on
v[0-9]+.[0-9]+.[0-9]+ tags (excludes pre-release tags). Workflow_dispatch
with version input for manual re-runs. 3-layer cache (setup-ocaml +
dune _build + restore-keys). Action SHAs pinned where lookup succeeded."

echo "=== Staging commit 5/6: dune-project deps + description sweep ==="
git add dune-project par_code.opam
git commit -m \
"feat(deps): declare cohttp-eio/tls-eio/digestif + sanitize description

- dune-project (depends ...): adds cohttp-eio, tls-eio, digestif as
  direct deps. These were already transitively available via par SDK
  (PAR's http_client uses them); declaring them direct ensures
  par_code.opam reflects reality and survives future par refactors.
- par_code.opam: regenerated by dune.
- Sanitize (bundled, separate sweep preferred per global rules):
  description 'Claude-Code-style terminal assistant' -> 'terminal-native
  coding assistant' to comply with global disclosure rule §2."

echo "=== Staging commit 6/6: docs + README sweep ==="
git add README.md CHANGES.md docs/DECISIONS.md
git commit -m \
"docs(v0.2.1): install rewrite + changelog + 4 DECISIONS entries

- README.md: Install section rewritten — one-line installer primary,
  opam source-pin demoted to 'Developer install'. Adds Platform support
  table (Windows v0.2.2, Intel Mac Rosetta, Alpine v0.2.3 callouts),
  Self-update section, Integrity model statement. Project layout adds
  scripts/. Status line: v0.2.0-dev -> v0.2.1-dev.
- CHANGES.md: new '## v0.2.1-dev — One-line install & self-update
  (UNRELEASED)' section at top with ### Added (8 bullets) and
  ### Changed (6 bullets).
- docs/DECISIONS.md: 4 new [2026-07-03] entries following the 6-field
  format (变更前/变更后/原因/影响范围/回退方式/已知限制):
    1. Linux bundle base: CentOS 7 + devtoolset-11
    2. par_code_upgrade HTTP client: Cohttp_eio direct (Par.Http_client
       is POST-only)
    3. Bundle libsqlite3 + libgmp next to par binary (R3 'do it right
       once' for v0.3.0 FTS5)
    4. v0.2.1 integrity model: HTTPS + SHA256 (transport check only)
- Sanitize (bundled): README line 6 'Claude-Code-style' ->
  'terminal-native, REPL-first'."

echo ""
echo "=== All 6 commits created. Review with: ==="
echo "  git log --oneline origin/main..HEAD"
echo "  git diff origin/main..HEAD --stat"
echo ""
echo "=== Push with: ==="
echo "  git push"
echo ""
echo "=== Undo all (keep changes staged): ==="
echo "  git reset --soft origin/main"
